Repository stolostron/config-policy-controller, pull requests merged in 2021-04, with the labels that each got.

#106 Remove SelfLink
  .github/workflows/kind.yml
  Makefile
  deploy/crds/policy.open-cluster-management.io_configurationpolicies_crd.yaml
  deploy/crds/v1/policy.open-cluster-management.io_configurationpolicies.yaml
  go.sum
  pkg/apis/policy/v1/configurationpolicy_types.go
  pkg/apis/policy/v1/zz_generated.deepcopy.go
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
Labels: approved, lgtm

#107 update deploy config
  Makefile
  build/run-e2e-tests.sh
  deploy/clusterrole_binding.yaml
  deploy/operator.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm

#108 change to WATCH_NAMESPACE
  Makefile
Labels: approved, lgtm

#112 add lease controller to report status as an addon
  Makefile
  cmd/manager/main.go
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/common/namespace_selection.go
  pkg/common/namespace_selection_test.go
  pkg/common/policyReader.go
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
  test/e2e/e2e_suite_test.go
  test/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm

#109 Enhance list compare
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
  test/e2e/case12_list_compare_test.go
  test/resources/case12_list_compare/case12_pod_create.yaml
  test/resources/case12_list_compare/case12_pod_inform.yaml
Labels: approved, dco-signoff: yes, lgtm

#113 enhance generic list check to use sort
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
  test/e2e/case12_list_compare_test.go
  test/resources/case12_list_compare/case12_role_create.yaml
  test/resources/case12_list_compare/case12_role_inform.yaml
Labels: approved, dco-signoff: yes, lgtm

#115 do not patch existing lists with the sorted version
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
  test/e2e/case7_no_spec_test.go
Labels: approved, dco-signoff: yes, lgtm

#116 templatized policies
  go.mod
  pkg/common/templates/clusterconfig_funcs.go
  pkg/common/templates/generic_lookup_func.go
  pkg/common/templates/k8sresource_funcs.go
  pkg/common/templates/templates.go
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
Labels: approved, dco-signoff: yes, lgtm

#114 Doc Update
  CONTRIBUTING.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test

#117 remove codecov scripts
  Makefile
  build/common/scripts/codecov.sh
Labels: approved, dco-signoff: yes, lgtm

#118 templatize e2e test
  Makefile
  test/crds/clusterclaims.cluster.open-cluster-management.io.yaml
  test/e2e/case13_templatization_test.go
  test/e2e/e2e_suite_test.go
  test/resources/case13_templatization/case13_clusterclaim.yaml
  test/resources/case13_templatization/case13_configmap.yaml
  test/resources/case13_templatization/case13_copysecret.yaml
  test/resources/case13_templatization/case13_lookup_secret.yaml
  test/resources/case13_templatization/case13_pod_nameFromClusterClaim.yaml
  test/resources/case13_templatization/case13_pod_name_verify.yaml
  test/resources/case13_templatization/case13_pod_name_verify_configmap.yaml
  test/resources/case13_templatization/case13_secret.yaml
  test/resources/case13_templatization/case13_unterminated.yaml
  test/resources/case13_templatization/case13_verifysecret.yaml
  test/resources/case13_templatization/case13_wrong_args.yaml
  test/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm

#121 templates gotest-1
  pkg/common/templates/k8sresource_funcs_test.go
  pkg/common/templates/templates.go
  pkg/common/templates/templates_test.go
Labels: approved, dco-signoff: yes, lgtm

#122 fix issues processing newlines in metadata
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  test/e2e/case13_templatization_test.go
  test/resources/case13_templatization/case13_lookup_cc.yaml
Labels: approved, dco-signoff: yes, lgtm
