Repository stolostron/config-policy-controller, pull requests merged in 2021-07, with the labels that each got.

#136 manual backport for issue 13182
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
Labels: dco-signoff: yes

#139 Show details in status message
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
Labels: dco-signoff: yes, lgtm

#140 fix sort compare bug and extra list items bug
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
  test/e2e/case12_list_compare_test.go
  test/resources/case12_list_compare/case12_role_create_small.yaml
  test/resources/case12_list_compare/case12_role_patch.yaml
  test/resources/case12_list_compare/case12_role_patch_inform.yaml
Labels: approved, dco-signoff: yes, lgtm

#141 fix config-ppolicy-ctrl addon name
  cmd/manager/main.go
Labels: approved, dco-signoff: yes, lgtm

#142 add additional release support
  .github/workflows/kind.yml
Labels: approved, dco-signoff: yes, lgtm

#144 refresh the build by updating the date in the README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm

#143 sort template in merge fn
  Makefile
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
  test/crds/oauths.config.openshift.io_crd.yaml
  test/e2e/case12_list_compare_test.go
  test/resources/case12_list_compare/case12_oauth_create.yaml
  test/resources/case12_list_compare/case12_oauth_patch.yaml
  test/resources/case12_list_compare/case12_oauth_verify.yaml
Labels: approved, dco-signoff: yes, lgtm

#145 Refactor mergeArray
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
Labels: approved, dco-signoff: yes, lgtm

#147 clean up code
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
  pkg/controller/configurationpolicy/configurationpolicy_utils.go
Labels: approved, dco-signoff: yes, lgtm

#148 Use the go-template-utils library
  go.mod
  go.sum
  pkg/common/templates/clusterconfig_funcs.go
  pkg/common/templates/generic_lookup_func.go
  pkg/common/templates/k8sresource_funcs.go
  pkg/common/templates/k8sresource_funcs_test.go
  pkg/common/templates/templates.go
  pkg/common/templates/templates_test.go
  pkg/controller/configurationpolicy/configurationpolicy_controller.go
Labels: approved, dco-signoff: yes, lgtm
