Repository stolostron/config-policy-controller, pull requests merged in 2021-02, with the labels that each got.

#86 Add Dockerfile.prow
  build/Dockerfile.prow
Labels: approved, lgtm

#85 Add Prow integration - 9370
  Makefile
  Makefile.prow
  build/Dockerfile
  build/Dockerfile.prow
  build/build.sh
Labels: approved, do-not-merge/hold

#89 Update OWNERS
  OWNERS
Labels: approved, lgtm

#88 Switch builds from master to main
  .travis.yml
Labels: approved

#87 Security compliance 9544
  SECURITY.md
Labels: approved

#91 Remove Travis Publish stage
  .travis.yml
Labels: approved, lgtm

#90 Update README
  README.md
Labels: approved, lgtm

#92 address CVE-2020-14040
  go.mod
  go.sum
Labels: approved, lgtm
